-- SmartDialer initial schema.
--
-- Conventions:
--   * Ids are TEXT, generated by IdGenerator (sequential, so runs replay comparably).
--   * All timestamps are INTEGER virtual milliseconds from the run's clock — never wall
--     clock. See DECISIONS.md D-003.
--   * Structured values (retry policy, metadata, reports) are TEXT holding JSON.
--   * Booleans are INTEGER 0/1; SQLite has no boolean type.

CREATE TABLE campaigns (
  id                        TEXT PRIMARY KEY,
  name                      TEXT    NOT NULL,
  status                    TEXT    NOT NULL,
  dialing_mode              TEXT    NOT NULL,

  -- Hard limits read by the safety engine on every dial.
  max_concurrent_calls      INTEGER NOT NULL,
  max_calls_per_second      REAL    NOT NULL,
  max_abandon_rate          REAL    NOT NULL,
  max_attempts_per_contact  INTEGER NOT NULL,

  retry_policy              TEXT    NOT NULL,  -- JSON RetryPolicy
  safety                    TEXT    NOT NULL,  -- JSON CampaignSafetyConfig
  provider_id               TEXT    NOT NULL,

  -- Non-null means the abandon-rate control paused predictive dialing and an operator
  -- must explicitly resume. The system never clears this by itself.
  predictive_paused_reason  TEXT,

  created_at                INTEGER NOT NULL,
  updated_at                INTEGER NOT NULL
);

CREATE TABLE contacts (
  id              TEXT PRIMARY KEY,
  campaign_id     TEXT    NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  name            TEXT    NOT NULL,
  phone_number    TEXT    NOT NULL,
  status          TEXT    NOT NULL,
  attempt_count   INTEGER NOT NULL DEFAULT 0,
  last_attempt_at INTEGER,
  next_attempt_at INTEGER,
  timezone        TEXT    NOT NULL DEFAULT 'UTC',
  metadata        TEXT    NOT NULL DEFAULT '{}',
  created_at      INTEGER NOT NULL,
  updated_at      INTEGER NOT NULL
);

-- The index behind contact reservation. The reservation statement filters on exactly
-- (campaign_id, status, next_attempt_at) and it runs on every dial, so this index is on
-- the hottest path in the system.
CREATE INDEX idx_contacts_dialable ON contacts (campaign_id, status, next_attempt_at);
CREATE INDEX idx_contacts_campaign_status ON contacts (campaign_id, status);

CREATE TABLE agents (
  id                   TEXT PRIMARY KEY,
  campaign_id          TEXT REFERENCES campaigns(id) ON DELETE SET NULL,
  name                 TEXT    NOT NULL,
  status               TEXT    NOT NULL,
  -- Deliberately no foreign key: calls reference agents and agents reference calls, and a
  -- real constraint here would create a cycle for no benefit. Consistency is maintained by
  -- the agent state machine, which is tested.
  current_call_id      TEXT,
  calls_handled        INTEGER NOT NULL DEFAULT 0,
  total_handle_time_ms INTEGER NOT NULL DEFAULT 0,
  last_state_change    INTEGER NOT NULL,
  created_at           INTEGER NOT NULL,
  updated_at           INTEGER NOT NULL
);

CREATE INDEX idx_agents_campaign_status ON agents (campaign_id, status);

CREATE TABLE calls (
  id               TEXT PRIMARY KEY,
  campaign_id      TEXT    NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  contact_id       TEXT    NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  -- No FK: the call row is written before its attempt row inside the same transaction.
  attempt_id       TEXT    NOT NULL,
  agent_id         TEXT REFERENCES agents(id) ON DELETE SET NULL,
  provider_id      TEXT    NOT NULL,
  provider_call_id TEXT,
  status           TEXT    NOT NULL,

  created_at       INTEGER NOT NULL,
  dialing_at       INTEGER,
  ringing_at       INTEGER,
  connected_at     INTEGER,
  ended_at         INTEGER,
  talk_duration_ms INTEGER,

  outcome          TEXT,
  failure_code     TEXT,
  failure_class    TEXT    NOT NULL DEFAULT 'NONE',
  abandoned        INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_calls_campaign_status ON calls (campaign_id, status);
CREATE INDEX idx_calls_contact ON calls (contact_id);
CREATE INDEX idx_calls_agent ON calls (agent_id);
CREATE INDEX idx_calls_created ON calls (created_at);

CREATE TABLE call_attempts (
  id                  TEXT PRIMARY KEY,
  call_id             TEXT    NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
  contact_id          TEXT    NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  campaign_id         TEXT    NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  attempt_number      INTEGER NOT NULL,
  started_at          INTEGER NOT NULL,
  ended_at            INTEGER,
  outcome             TEXT,
  failure_code        TEXT,
  failure_class       TEXT    NOT NULL DEFAULT 'NONE',
  retry_scheduled_for INTEGER
);

CREATE INDEX idx_attempts_contact ON call_attempts (contact_id, attempt_number);
CREATE INDEX idx_attempts_campaign ON call_attempts (campaign_id);

CREATE TABLE events (
  -- AUTOINCREMENT gives a strictly monotonic sequence even across deletes, which is what
  -- lets an SSE client resume with "everything after seq N" and not silently miss events.
  seq         INTEGER PRIMARY KEY AUTOINCREMENT,
  id          TEXT    NOT NULL UNIQUE,
  type        TEXT    NOT NULL,
  at          INTEGER NOT NULL,
  severity    TEXT    NOT NULL,
  message     TEXT    NOT NULL,
  campaign_id TEXT,
  contact_id  TEXT,
  call_id     TEXT,
  agent_id    TEXT,
  provider_id TEXT,
  metadata    TEXT    NOT NULL DEFAULT '{}'
);

CREATE INDEX idx_events_at ON events (at);
CREATE INDEX idx_events_type ON events (type);
CREATE INDEX idx_events_campaign ON events (campaign_id);
CREATE INDEX idx_events_call ON events (call_id);
CREATE INDEX idx_events_severity ON events (severity);

CREATE TABLE provider_configs (
  id         TEXT PRIMARY KEY,
  driver     TEXT    NOT NULL,
  config     TEXT    NOT NULL DEFAULT '{}',  -- JSON MockProviderConfig
  updated_at INTEGER NOT NULL
);

CREATE TABLE simulation_runs (
  id          TEXT PRIMARY KEY,
  scenario    TEXT    NOT NULL,
  seed        INTEGER NOT NULL,
  config      TEXT    NOT NULL,  -- JSON SimulationConfig
  status      TEXT    NOT NULL,
  started_at  INTEGER NOT NULL,
  finished_at INTEGER,
  report      TEXT             -- JSON SimulationReport, written on completion
);

CREATE INDEX idx_simulation_runs_started ON simulation_runs (started_at);
